name: Concurrency Testing
on: workflow_dispatch
#concurrency: concurrency-testing
concurrency:
  group: concurrency-testing
  cancel-in-progress: true

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Some step
        run: sleep 50
        timeout-minutes: 1