name: Eighth workflow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        type: string
        required: true
        default: "Hello World"
      selectCustom:
        description: Select value
        type: choice
        required: true
        options:
          - Value 1
          - Value 2
          - Value 3
        default: Value 2
      checkCustom:
        description: Check
        type: boolean
        required: false

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Event vars
        run: |
          echo "Title: ${{ inputs.titleCustom }}"
          echo "Select: ${{ inputs.selectCustom }}"
          echo "Check: ${{ inputs.checkCustom }}"