
name: Third workflow
on: [push]
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory
        run: |
          pwd
          ls -la
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Display working directory
        run: |
          pwd
          ls -la
