name: Twelve workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    environment: "Staging"
    steps:
      - name: Our Vars and Secrets
        run: |
          echo '${{ vars.TEST_STATUS }}'
          echo '${{ secrets.TEST_PASSWORD }}'
